In [20]:
import numpy as np
import tensorflow as tf 
from collections import deque
import random
import pdb
from replay_memory import ReplayMemory
from AC_networks_tf import ActorNet, CriticNet
from test_game import test_env
from info_obj import info_holder
import os
import gym

game_name = 'CartPole-v0'
#game_name = 'LunarLander-v2'
#game_name = 'MountainCar-v0'
game = gym.make(game_name)
state_dim = game.observation_space.shape[0]
action_dim = game.action_space.n
save_dir = './Results/'+ game_name[:-3] + '/net/'
string = 'hidden layers: '
with open(save_dir + 'params.txt', 'r') as f:
    while True:
        xa = f.readline()
        if string in xa:
            hid_lay = int(xa[len(string):])
            break
MAX_STEP = 1000
LEARNING_RATE = 0
TAU = 0
ENTROPY_BETA = 0
eps = 0
info = info_holder()
try:
    actor
except:
    pass
else:
    actor.reset_net()
try:
    critic
except:
    pass
else:
    critic.reset_net()

graph = tf.Graph()
with graph.as_default():
    info.graph = graph
    info.dim_s = state_dim
    info.dim_a = action_dim
    info.act_hid_layers = np.array([16])
    info.crit_hid_layers = np.array([16])
    info.learning_rate = LEARNING_RATE
    info.tau = TAU
    info.entropy_beta = ENTROPY_BETA
    actor = ActorNet(info)
    critic = CriticNet(info)

EP = 10000 - 1

with tf.Session(graph=graph) as sess:
    
    actor.set_up(sess)
    critic.set_up(sess)
    sess.run(tf.global_variables_initializer())
    
    saver = tf.train.Saver()
    filename = save_dir + 'Episod_' + str(EP) + '.chk'
    saver.restore(sess, filename)
    
    s = game.reset()
    a = actor.take_action(s.reshape(-1,info.dim_s))
    s2, r, terminal, report = game.step(a)
    ep_reward = 0
    for st in range(MAX_STEP):
        game.render()
        a = actor.take_action(s.reshape(-1,info.dim_s))
        s2, r, terminal, report = game.step(a)
        s = s2
        ep_reward += (1.*r)
        print(actor.give_policy(s.reshape(-1,info.dim_s)))
        if terminal:
            print('terminated')
            break
    print(r)
    print('reward:%f' %np.mean(ep_reward))

[2016-12-31 18:50:49,493] Making new env: CartPole-v0


[[ 0.96625215  0.03374786]]
[[ 0.81559634  0.18440367]]
[[ 0.38561535  0.61438465]]
[[ 0.83159727  0.16840266]]
[[ 0.41525283  0.58474714]]
[[ 0.84968942  0.15031064]]
[[ 0.45217189  0.54782808]]
[[ 0.86935085  0.13064915]]
[[ 0.49720377  0.50279617]]
[[ 0.1214297   0.87857026]]
[[ 0.51151443  0.48848557]]
[[ 0.12608886  0.87391108]]
[[ 0.51924336  0.48075664]]
[[ 0.89582247  0.10417749]]
[[ 0.55990583  0.44009417]]
[[ 0.14980796  0.85019207]]
[[ 0.57139468  0.42860523]]
[[ 0.15444994  0.84555006]]
[[ 0.5779177   0.42208228]]
[[ 0.15664563  0.84335434]]
[[ 0.57975996  0.42024001]]
[[ 0.15639469  0.84360534]]
[[ 0.57704735  0.42295259]]
[[ 0.91399455  0.08600549]]
[[ 0.60797113  0.3920289 ]]
[[ 0.17426203  0.82573801]]
[[ 0.61192268  0.38807738]]
[[ 0.92553729  0.07446274]]
[[ 0.64896572  0.35103428]]
[[ 0.93700683  0.0629932 ]]
[[ 0.69506496  0.3049351 ]]
[[ 0.24453534  0.75546467]]
[[ 0.0421912   0.95780879]]
[[ 0.23482852  0.76517147]]
[[ 0.69922101  0.3007789 ]]
[[ 0.94850343  0.051

AttributeError: 'NoneType' object has no attribute 'flip'

In [16]:
import gym
#game_name = 'CartPole-v0'
#game_name = 'LunarLander-v2'
#game_name = 'MountainCar-v0'
game = gym.make(game_name)
state_dim = game.observation_space.shape[0]
action_dim = game.action_space.n
ep_reward = 0
a= 0
for st in range(1000):
    game.render()
    a = 1 - a
    print(action_dim)
    s2, r, terminal, report = game.step(a)
    s = s2
    ep_reward += (1.*r)
    if terminal:
        print('terminated')
        break


[2016-12-31 17:43:10,045] Making new env: CartPole-v0


2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
terminated
