In [3]:
import numpy as np
import tensorflow as tf 
from collections import deque
import random
import pdb
from replay_memory import ReplayMemory
from AC_networks_tf import ActorNet, CriticNet
from test_game import test_env
from info_obj import info_holder
import os
import gym

#game_name = 'CartPole-v0'
game_name = 'LunarLander-v2'
#game_name = 'MountainCar-v0'
game = gym.make(game_name)
state_dim = game.observation_space.shape[0]
action_dim = game.action_space.n
save_dir = './Results/'+ game_name[:-3] + '/net/'
string = ['actor hidden layers: ', 'critic hidden layers: ']
act_hid_lay = 32
crit_hid_lay = 16
with open(save_dir + 'params.txt', 'r') as f:
    xa = f.readline()
    while xa:
        if string[0] in xa:
            act_hid_lay = [int(xb) for xb in xa[len(string[0]):].split()]
        if string[1] in xa:
            crit_hid_lay = [int(xb) for xb in xa[len(string[1]):].split()]
        xa = f.readline()
MAX_STEP = 1000
LEARNING_RATE = 0
TAU = 0
ENTROPY_BETA = 0
eps = 0
info = info_holder()
try:
    actor
except:
    pass
else:
    actor.reset_net()
try:
    critic
except:
    pass
else:
    critic.reset_net()

graph = tf.Graph()
with graph.as_default():
    info.graph = graph
    info.dim_s = state_dim
    info.dim_a = action_dim
    info.act_hid_layers = np.array(act_hid_lay)
    info.crit_hid_layers = np.array(crit_hid_lay)
    info.learning_rate = LEARNING_RATE
    info.tau = TAU
    info.entropy_beta = ENTROPY_BETA
    actor = ActorNet(info)
    critic = CriticNet(info)

EP = 15000 - 1

with tf.Session(graph=graph) as sess:
    
    actor.set_up(sess)
    critic.set_up(sess)
    sess.run(tf.global_variables_initializer())
    
    saver = tf.train.Saver()
    filename = save_dir + 'Episod_' + str(EP) + '.chk'
    saver.restore(sess, filename)
    
    s = game.reset()
    a = actor.take_action(s.reshape(-1,info.dim_s))
    s2, r, terminal, report = game.step(3)
    ep_reward = 0
    for st in range(MAX_STEP):
        game.render()
        a = actor.take_action(s.reshape(-1,info.dim_s))
        s2, r, terminal, report = game.step(a)
        s = s2
        ep_reward += (1.*r)
        print(actor.give_policy(s.reshape(-1,info.dim_s)))
        if terminal:
            print('terminated')
            break
    print(r)
    print('reward:%f' %np.mean(ep_reward))

[2017-01-02 02:56:28,785] Making new env: LunarLander-v2


[[ 0.30076981  0.13686028  0.41831633  0.14405361]]
[[ 0.300771    0.13685888  0.41832036  0.14404979]]
[[ 0.30077136  0.13685529  0.41832426  0.14404909]]
[[ 0.30077088  0.13685645  0.41832078  0.14405191]]
[[ 0.30077192  0.13685481  0.41832477  0.14404845]]
[[ 0.30077234  0.1368514   0.4183287   0.14404757]]
[[ 0.30077353  0.13685019  0.41833273  0.14404353]]
[[ 0.30077398  0.13684689  0.41833666  0.14404248]]
[[ 0.30077535  0.13684615  0.4183408   0.14403774]]
[[ 0.30077583  0.13684295  0.41834477  0.14403649]]
[[ 0.30077562  0.13684358  0.41834316  0.1440376 ]]
[[ 0.30077699  0.13684283  0.4183473   0.14403288]]
[[ 0.30077639  0.13683687  0.41835108  0.14403559]]
[[ 0.30077592  0.13683982  0.41834721  0.14403702]]
[[ 0.30077642  0.13683662  0.41835123  0.14403577]]
[[ 0.30077687  0.13683337  0.41835523  0.14403453]]
[[ 0.30077672  0.13683403  0.41835332  0.14403602]]
[[ 0.30077654  0.13683487  0.41835126  0.14403734]]
[[ 0.30077609  0.13682924  0.41835502  0.14403966]]
[[ 0.3007765

In [6]:
with open(save_dir + 'params.txt', 'r') as f:
    for i in range(20):
        xa = f.readline()
        if xa:
            print(xa)


Learning rate = 0.100000

lr decay = 1.000000

hidden layers: 32

update cycle: 1

