In [6]:
import numpy as np
import tensorflow as tf 
from collections import deque
import random
import pdb
from replay_memory import ReplayMemory
from AC_networks_tf import ActorNet, CriticNet
from test_game import test_env
from info_obj import info_holder
import os
import gym

#game_name = 'CartPole-v0'
game_name = 'LunarLander-v2'
#game_name = 'MountainCar-v0'
game = gym.make(game_name)
state_dim = game.observation_space.shape[0]
action_dim = game.action_space.n
save_dir = './Results/'+ game_name[:-3] + '/net/'
string = ['actor hidden layers: ', 'critic hidden layers: ']
act_hid_lay = [32, 32]
crit_hid_lay = [16, 16]
with open(save_dir + 'params.txt', 'r') as f:
    xa = f.readline()
    while xa:
        if string[0] in xa:
            act_hid_lay = [int(xb) for xb in xa[len(string[0]):].split()]
        if string[1] in xa:
            crit_hid_lay = [int(xb) for xb in xa[len(string[1]):].split()]
        xa = f.readline()
#act_hid_lay = [32, 32]
#crit_hid_lay = [16, 16]
MAX_STEP = 1000
LEARNING_RATE = 0
TAU = 0
ENTROPY_BETA = 0
eps = 0
info = info_holder()
try:
    actor
except:
    pass
else:
    actor.reset_net()
try:
    critic
except:
    pass
else:
    critic.reset_net()

graph = tf.Graph()
with graph.as_default():
    info.graph = graph
    info.dim_s = state_dim
    info.dim_a = action_dim
    info.act_hid_layers = np.array(act_hid_lay)
    info.crit_hid_layers = np.array(crit_hid_lay)
    info.learning_rate = LEARNING_RATE
    info.tau = TAU
    info.entropy_beta = ENTROPY_BETA
    actor = ActorNet(info)
    critic = CriticNet(info)

EP = 6000 - 1

with tf.Session(graph=graph) as sess:
    
    actor.set_up(sess)
    critic.set_up(sess)
    sess.run(tf.global_variables_initializer())
    
    saver = tf.train.Saver()
    filename = save_dir + 'Episod_' + str(EP) + '.chk'
    saver.restore(sess, filename)
    
    s = game.reset()
    a = actor.take_action(s.reshape(-1,info.dim_s))
    s2, r, terminal, report = game.step(3)
    ep_reward = 0
    for st in range(MAX_STEP):
        game.render()
        a = actor.take_action(s.reshape(-1,info.dim_s))
        s2, r, terminal, report = game.step(a)
        s = s2
        ep_reward += (1.*r)
        print(actor.give_policy(s.reshape(-1,info.dim_s)))
        if terminal:
            print('terminated')
            break
    print(r)
    print('reward:%f' %np.mean(ep_reward))

[2017-01-04 04:54:00,720] Making new env: LunarLander-v2


[[ 0.0021311   0.00389473  0.3851307   0.60884351]]
[[ 0.00194951  0.00465942  0.21514381  0.77824724]]
[[ 0.00194167  0.00387514  0.79409802  0.20008513]]
[[ 0.00280908  0.01361054  0.26466921  0.71891117]]
[[ 0.00240184  0.01121254  0.84892392  0.13746159]]
[[ 0.00387085  0.07053202  0.16382816  0.761769  ]]
[[ 0.0044512   0.08032103  0.73308104  0.1821467 ]]
[[ 0.00590909  0.18683603  0.46195853  0.34529635]]
[[ 0.00435363  0.37349403  0.0813612   0.54079121]]
[[ 0.00485477  0.0776284   0.36312243  0.55439448]]
[[ 0.00308009  0.05479607  0.87440431  0.06771959]]
[[ 0.00346249  0.07381815  0.84580159  0.07691769]]
[[ 0.00101104  0.00392269  0.97363573  0.02143045]]
[[ 0.0038343   0.04285116  0.757177    0.19613755]]
[[ 0.00376147  0.04369994  0.77597445  0.17656419]]
[[ 0.00560282  0.14326611  0.37435797  0.47677302]]
[[ 0.0045798   0.23893434  0.11391273  0.64257312]]
[[ 0.00549592  0.3122704   0.5371204   0.14511323]]
[[ 0.00555684  0.42177802  0.42134562  0.15131959]]
[[ 0.0053397

In [6]:
with open(save_dir + 'params.txt', 'r') as f:
    for i in range(20):
        xa = f.readline()
        if xa:
            print(xa)


Learning rate = 0.100000

lr decay = 1.000000

hidden layers: 32

update cycle: 1

